apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-app
  template:
    metadata:
      labels:
        app: cache-app
    spec:
      containers:
      - name: cache-app
        image: shferguacr.azurecr.io/cache-app:v1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: development
---
apiVersion: v1
kind: Service
metadata:
  name: cache-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: cache-app
